pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET'
  inputs:
    version: '6.0.0-rc.1'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore referenced NuGet packages'
  inputs:
    command: 'restore'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --no-build --collect "Code coverage"'

- task: CopyFiles@2
  displayName: 'Copy artifacts to staging'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/$(buildConfiguration)/**/?(*.nupkg)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
    
- task: PublishPipelineArtifact@1
  displayName: 'Publish artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop